### ISSUE TITLE
Can not run anything 

### ISSUE THREAD

**Issue by sridhar9999** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#10]
When I run the code for that example data you provided in test_sample0 I can't

**Comment by sridhar9999** [comment]
could u please link me an article or youtube link for tutoriaals of this project

**Comment by ChenyangLEI** [comment]
This is our paper.  
https://cqf.io/papers/Fully_Automatic_Video_Colorization_CVPR2019.pdf

Thank you.
