### ISSUE TITLE
I'm working on CUDA10 and how can I load the op library in flow_warp.py?

### ISSUE THREAD

**Issue by Lawrrance** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#12]
I'm working on CUDA10 and how can I load the op library in flow_warp.py?
An error occurred like this
![P0BLP63${3{5QTTPMHTBHTQ](https://user-images.githubusercontent.com/35630999/80357606-cbe93700-88ad-11ea-81d5-d203ed25c373.png)
I cannot change the version of CUDA right now,and is there any solution to fix it?

**Comment by ChenyangLEI** [comment]
Sorry, I did not test it on Cuda 10 before. 
Maybe you can:
1) Use other function to warp the image with optical flow.
2) Use the first network for testing.

**Comment by wangyr4151** [comment]
Hello, I also met the same problem in training. Have you solved it?

**Comment by wangyr4151** [comment]
### envs:
cuda10.1
tensorflow-gpu==1.14.0<br>
hello, i have meet same question, can you tell me how to generate the **flow_warp.so** file in cuda10.1 , or provided your script to generate the files ,thx!

**Comment by ChenyangLEI** [comment]
Sorry! I did not notice your comment. Also, I did not test it on Cuda 10 before, maybe you can modify the warping function for optical flow by using https://www.tensorflow.org/addons/api_docs/python/tfa/image/dense_image_warp.

**Comment by wangyr4151** [comment]
> Sorry! I did not notice your comment. Also, I did not test it on Cuda 10 before, maybe you can modify the warping function for optical flow by using https://www.tensorflow.org/addons/api_docs/python/tfa/image/dense_image_warp.

Thank you very much for your reply. I am going to have a try.

**Comment by rishesh007** [comment]
@wangyr4151 I am also facing the same issue and not able to find the solution. Can you please tell me what modification you had done and share a similar resource for that.

I appreciate any help you can provide.

Env Specs:
tensorflow==1.13.2
cuda==11.0
