### ISSUE TITLE
AttributeError: module 'scipy.misc' has no attribute 'imread'

### ISSUE THREAD

**Issue by xstrauss** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#14]
When I run this code;

> !python main_woflow.py --model ckpt_woflow --use_gpu 1 --test_img /content/frames

I'm getting this error;

>  File "main_woflow.py", line 129, in <module>
    im=np.float32(scipy.misc.imread(test_img, 'L'))/255.0
AttributeError: module 'scipy.misc' has no attribute 'imread'

**Comment by ChenyangLEI** [comment]
try this:
pip install scipy==1.1.0
