### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by AlexeyRogS** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#15]
Hi! 
I wanna use our code for my course project but it is not clear how data should be arrange. Is directory JPEGImages supposed to have gray frames? If so than where should i put colored (true) frames? Also it is not clear how to "generate the optical flow by PWC-Net".

Could you please clarify that?

**Comment by ChenyangLEI** [comment]
1. For training, the color frame will be transferred to gray frames internally. For the data, please following this format:
+data
-----+JPEGImages
----------------+480p
---------------------+VideoFrames1
---------------------+VideoFrames2
-----+FLOWImages
----------------+Forward
-----------------------+VideoFrames1
-----------------------+VideoFrames2
----------------+Backward
-----------------------+VideoFrames1
-----------------------+VideoFrames2
-----+FLOWImages_GRAY
--------------------+Forward
----------------------------+VideoFrames1
----------------------------+VideoFrames2
--------------------+Backward
----------------------------+VideoFrames1
----------------------------+VideoFrames2


2. The optical flow is generated by PWC-Net:
https://github.com/NVlabs/PWC-Net
