### ISSUE TITLE
download

### ISSUE THREAD

**Issue by wangyr4151** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#16]
Hello, Sorry to bother you, but I really can't download the weight files "VGG_Model/ imagenet-vGG -verydeep-19.mat" and "CKpt_woflow. zip". Can you send it to my mailbox if convenient? My email address is 2595421194@qq.com
thank you very much.

**Comment by ChenyangLEI** [comment]
It seems that the file is too large to send through email. Is it because you cannot visit Google Drive or other technical problem?

**Comment by wangyr4151** [comment]
Thank you very much for your reply. I have downloaded the weight file correctly a few days ago. Now I have a new question. Because your README file doesn't match the code, I don't know how to train my own data. Can you explain it to me? Thank you again.

**Comment by ChenyangLEI** [comment]
Basically, you need to put the image files, optical flow files for RGB data, optical flow for gray data to the folders. 
+data
-----+JPEGImages
----------------+480p
---------------------+VideoFrames1
---------------------+VideoFrames2
-----+FLOWImages
----------------+Forward
-----------------------+VideoFrames1
-----------------------+VideoFrames2
----------------+Backward
-----------------------+VideoFrames1
-----------------------+VideoFrames2
-----+FLOWImages_GRAY
--------------------+Forward
----------------------------+VideoFrames1
----------------------------+VideoFrames2
--------------------+Backward
----------------------------+VideoFrames1
----------------------------+VideoFrames2
