### ISSUE TITLE
question in download VGG_Model/imagenet-vgg-verydeep-19.mat

### ISSUE THREAD

**Issue by lccssr** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#17]
Hello，thanks for your project.
I meet an error in download_models.py,line34
`download_file_from_google_drive('0B_B_FOgPxgFLRjdEdE9NNTlzUWc', 'VGG_Model/imagenet-vgg-verydeep-19.mat')`

FileNotFoundError: [Errno 2] No such file or directory: 'VGG_Model/imagenet-vgg-verydeep-19.mat'

I changed `VGG_Model/imagenet-vgg-verydeep-19.mat`  with `imagenet-vgg-verydeep-19.mat` and download sucessful, then move it in VGG_Model. So I think if you can justify your code in download_models.py.

**Comment by ChenyangLEI** [comment]
I see. Thank you for your warm reminder!
