### ISSUE TITLE
Trainging settings

### ISSUE THREAD

**Issue by dwangxxx** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#19]
Hello, sorry to bother you! I've read your paper and source code recently. You mentioned that you train the colorization model firstly, and then the colorization model and refinement model are trained jointly. But the main_whole.py file may only include the joint training code? 
If I want to reproduce the result, do I need to add a new file to train the colorization network firstly? 
And in the main_whole.py file, the pre-trained model of colorization network may not be loaded. After the colorization network is trained, should I load the pre-trained model of colorization network when training the whole network?
Looking forward to your apply! Thank you!

**Comment by ChenyangLEI** [comment]
1. You can modify line 246 "if epoch > 0:" to "if epoch > YOUR WANTED EPOCH" if you want to train together.

2. You can also load the colorization network first, then train two networks jointly.

**Comment by dwangxxx** [comment]
> 1. You can modify line 246 "if epoch > 0:" to "if epoch > YOUR WANTED EPOCH" if you want to train together.
> 2. You can also load the colorization network first, then train two networks jointly.

Ok, Thank you!
