### ISSUE TITLE
ckpt_woflow.zip can't be download

### ISSUE THREAD

**Issue by RayestGeeta** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#2]
hello, i can't connect https://docs.google.com/uc?export=download. Is it bad requests? error 400. Could you solve it? Thank you

**Comment by ChenyangLEI** [comment]
Hi, did you try "python download_models.py" to download the model? 

If you still can't download it, maybe you could try to connect  "https://drive.google.com/file/d/1yL8x7RL_82Mvyh_ebmh3uF6wiPOO2dU7/view?usp=sharing".

Thank you.

**Comment by RayestGeeta** [comment]
Thank you. That's ok.
