### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by dwangxxx** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#20]
Hello, I've tried to train this whole model, but I found that the training speed is very slow because the KNN calculating. Is there any other choice? Thank you!

**Comment by ChenyangLEI** [comment]
Yes, the KNN calculating is quite slow. 
1. You can try to train on downsampled images (e.g., half resolution) and then finetune on full resolution images
2. You can try to save the calculation results of KNN first.

**Comment by dwangxxx** [comment]
> Yes, the KNN calculating is quite slow.
> 
> 1. You can try to train on downsampled images (e.g., half resolution) and then finetune on full resolution images
> 2. You can try to save the calculation results of KNN first.

Ok, Thank you!
