### ISSUE TITLE
Fail to download  VGG_19model and ckpt-woflow.zip

### ISSUE THREAD

**Issue by royal-ai** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#22]
I try to download the VGG_19 model by run 
`python download_VGG.py`
And the connection error happened.
![image](https://user-images.githubusercontent.com/47621594/98440814-e7bf7680-2135-11eb-80fb-34e097395ae8.png)
I can browse Google and Youtobe. Is the download link invalid? Or may I have some wrong operation?
look forward to your reply
good wish!

**Comment by ChenyangLEI** [comment]
Can you try this?

https://drive.google.com/file/d/1Hm_VS5Acxge3t0TUhKFZa8c0QFw2TTr_/view?usp=sharing

**Comment by royal-ai** [comment]
Yeah, it works. I can download the model from this link. Thanks.

**Comment by royal-ai** [comment]
Can you give the download link of ckpt_woflow, too?

**Comment by royal-ai** [comment]
![image](https://user-images.githubusercontent.com/47621594/99018704-b3184880-2595-11eb-93c0-185521a3e9bc.png)

**Comment by royal-ai** [comment]
Thanks, It works,can you provide the link of the ckpt-woflow.zip?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chenyang LEI"<notifications@github.com&gt;; 
发送时间: 2020年11月10日(星期二) 晚上11:23
收件人: "ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity"<Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity@noreply.github.com&gt;; 
抄送: "⊙ω⊙"<1039661493@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity] Fail to download  VGG_19model (#22)





 
Can you try this?
 
https://drive.google.com/file/d/1Hm_VS5Acxge3t0TUhKFZa8c0QFw2TTr_/view?usp=sharing

**Comment by ChenyangLEI** [comment]
https://drive.google.com/file/d/1yL8x7RL_82Mvyh_ebmh3uF6wiPOO2dU7/view?usp=sharing
