### ISSUE TITLE
pretrained model of 'hyper_unet'

### ISSUE THREAD

**Issue by ZYzhouya** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#24]
Thanks for your nice work!

Could you please provide the pretrained model of 'hyper_unet' ?

**Comment by ChenyangLEI** [comment]
Sorry for the late reply as I do not notice it.

We do not have this pretrained model. The image colorization part is not in our paper. It is just for convenience for users. Hence, we do not train Hyper_unet.
