### ISSUE TITLE
If is the eval code can be AVALIABLE.

### ISSUE THREAD

**Issue by Yugt4732** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#25]
Hello， your work is so interesting. I wanna know, how can i reach the eval work as you do. whats the data for eval? And how to do for eval video data？

**Comment by ChenyangLEI** [comment]
Sorry for the late reply as I do not notice this issue. 

For the dataset, we use the release version of [Lai et al.](https://github.com/phoenix104104/fast_blind_video_consistency).

For the metric, we use [LPIPS](https://github.com/richzhang/PerceptualSimilarity) and PSNR, SSIM.
