### ISSUE TITLE
./lib/flow_warp.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by yyang181** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#26]
It seems like flow_warp.so was not compiled with tensorflow_framework.so dynamic lib. Is there any solution to this error?

**Comment by Jeff-Wu97** [comment]
Hi, I got the same error. Have you fixed the problem?

**Comment by yyang181** [comment]
> Hi, I got the same error. Have you fixed the problem?

Yep. I just google "flow_warp.so" and found that this file was generated by ATEN, https://github.com/HCPLab-SYSU/ATEN.
What we need to do is just follow the instruction in readme on how to **Compile flow_warp ops**. After done, just replace the old flow_warp.so with new one, and please enjoy. 

**Compile flow_warp ops(optional). The flow_warp.so have been generated(Ubuntu14.04, gcc4.8.4, python3.6, tf1.4). To compile flow_warp ops, you can excute the code as follows:**
