### ISSUE TITLE
Refinement network: g

### ISSUE THREAD

**Issue by mattclifford1** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#3]
Is it possible to have a script for the refinement network so that I can run the colourisation output through this multiple times as mentioned in your paper to gain better temporal coherence?

**Comment by ChenyangLEI** [comment]
It's OK for refine the output multiple times. But the improvement will not be as large as the first refinement. Thanks.

**Comment by mattclifford1** [comment]
Thanks for your reply, would you be able to make a script for this, or if you provide the network definition and weights to download I can write a script for you for everyone to use?

**Comment by ChenyangLEI** [comment]
Sure. You could use the "main_whole.py" to run this ckpt. The usage is similar to the "woflow" version. 

I upload the ckpt on google drive: 
https://drive.google.com/file/d/1u1w1mhcWVtrTJxZ9hg-FJ3bqV676skod/view?usp=sharing

**Comment by mattclifford1** [comment]
Perfect! thanks so much for this :)
