### ISSUE TITLE
Video colorization

### ISSUE THREAD

**Issue by tuananh1007** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#4]
I tried to run your model on video followed your instruction. However, it shows the error:

OSError: cannot identify image file 'test_video/girl_video.mp4'

I have tried with other videos, but still not run. Do I need to convert it to a specific video format? 

Thank you so much.

**Comment by ChenyangLEI** [comment]
Hi, 

You need to split the mp4 video to frames by yourself and save frames in one folder. 

Thank you.

**Comment by tuananh1007** [comment]
Thank you so much. I will try it.
