### ISSUE TITLE
Download.py cant be downloaded

### ISSUE THREAD

**Issue by panu135** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#8]
Download.py is not downloaded
Even the link provided by you i.e.ckpt is also not working please help 
Please tell the steps to download.

**Comment by ChenyangLEI** [comment]
Hi,

I check the download_models.py. I can download the models easily by python download_models.py.

You could also download the models from these links. 

https://drive.google.com/file/d/1Hm_VS5Acxge3t0TUhKFZa8c0QFw2TTr_/view?usp=sharing

https://drive.google.com/file/d/1u1w1mhcWVtrTJxZ9hg-FJ3bqV676skod/view?usp=sharing

https://drive.google.com/file/d/1yL8x7RL_82Mvyh_ebmh3uF6wiPOO2dU7/view?usp=sharing
