### ISSUE TITLE
its not running

### ISSUE THREAD

**Issue by sridhar9999** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#9]
I treid to run your code on your example dataset but it shows me nothing coud please help me to run this 
![Screenshot (29)](https://user-images.githubusercontent.com/24309312/77681975-2bf17280-6fbc-11ea-82f6-706c4114145f.png)

**Comment by ChenyangLEI** [comment]
Hi, please run it at "sidda/color".

The results should be generated at sidda/color/ckpt_woflow/

**Comment by sridhar9999** [comment]
it still doing nothing bro
do u have google colab notebook on this if u have please link me thanks  
![Screenshot (30)](https://user-images.githubusercontent.com/24309312/77991206-d5c85a80-7340-11ea-9f2e-3611dfb57b93.png)

**Comment by ChenyangLEI** [comment]
Sorry I don't have google Colab. Can you check the folder "test_sample0"? Maybe the images are not download.

**Comment by sridhar9999** [comment]
images are downloaded all 4 frames are there and it is not giving any errors  but simply proceeds to the main dir as shown in cmd
is there any way to trouble shoot this

**Comment by ChenyangLEI** [comment]
Maybe you can try put several "print("This is a checkpoint.")" to check the location where the programm stop.

I test the code yesterday and it could run successfully.

**Comment by sridhar9999** [comment]
ok if you dont mind asking can u make a video on this a short video that would be more helpful for me thanks a million

**Comment by ChenyangLEI** [comment]
The videos are shown in this project website.
https://leichenyang.weebly.com/project-color.html

**Comment by sridhar9999** [comment]
i mmean a tutorial video while u run on your system

**Comment by ChenyangLEI** [comment]
There is nothing special for my implementation. I run the code directly like you.

I thought you could print the **img_names** at line 107 to check img_names since you are using **windows**.


if not len(test_img):
    img_names = utils.get_names(test_dir)
    ind=0
    print(img_names) #add this line to main_woflow.py!

**Comment by sridhar9999** [comment]
i will do that i am not a code guy im a ui designer so know too less about code thats why 
i will do as u said

**Comment by sridhar9999** [comment]
i did it as u said but nothing showed up 
have a look
![Screenshot (31)](https://user-images.githubusercontent.com/24309312/78110863-578bb700-7419-11ea-97a3-64c57e76b939.png)
![Screenshot (32)](https://user-images.githubusercontent.com/24309312/78110867-5a86a780-7419-11ea-8977-909295b16a88.png)
![Screenshot (33)](https://user-images.githubusercontent.com/24309312/78110878-5ce90180-7419-11ea-882f-e5b7cb742ad4.png)

**Comment by sridhar9999** [comment]
i did but didnt show up the log

**Comment by ChenyangLEI** [comment]
then it might because you need to use another method to read files. Our code is tested on **ubuntu** instead of windows. Can you try:
python main_woflow.py --model ckpt_woflow --use_gpu 1 --test_img test_sample0/frame_000980.jpg

**Comment by sridhar9999** [comment]
still not working bro

**Comment by sridhar9999** [comment]
do u know how to create google colab

**Comment by ChenyangLEI** [comment]
Sorry I do not know. Besides, no more specific thing is required to run this code. Many people run it easily on **ubuntu**. I didn't test it on **window**.  I still believe that it would be better if you put several "print("This is a checkpoint.")" to check the location where the programm stop. After doing it, I might know what is the problem. It is impossible for me to debug without any warning or error.

**Comment by sridhar9999** [comment]
where i have to edit the print code in the code
